default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: "apricot_pit_pg_user"
  password: "H9ZgwRKrrgnI3G0vWooHp0ITHou1hddD"
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: my_dashboard_api_development

test:
  <<: *default
  database: my_dashboard_api_test

production:
  <<: *default
  database: mysite_production
